/**
 * BrokerAdapter — the contract every broker implementation honors.
 *
 * SPEC: docs/specs/live-trade-broker-integration.md §3.1 unit 4, §5
 *       contracts. Equity-first (Alpaca + paper); crypto branch is a
 *       deliberate stub until Phase B.crypto+.
 *
 * Why this lives as types-only:
 *   The interface is the substrate the daemon routes through. Multiple
 *   implementations (PaperBrokerAdapter, AlpacaAdapter, future Kraken/
 *   Hyperliquid) plug into it. Keeping the contract in a types-only file
 *   means anyone reading the daemon's adapter resolution can see the
 *   surface area without scanning implementation files for behavior.
 *
 * Idempotency contract — load-bearing (SPEC §7 item 3):
 *   Every `placeOrder` carries a `clientOrderId` (UUID generated by the
 *   caller). The broker MUST dedupe by this ID. A network retry on the
 *   same `clientOrderId` must NOT open a duplicate position. Failing to
 *   honor this contract risks doubled positions on real money.
 */

/**
 * Venues this codebase has a wired BrokerAdapter for (or is planning
 * to). Crypto venues land as stubs until Phase B.crypto+ — keeping them
 * in the union explicitly is preferable to a wide `string` because
 * exhaustive `switch` checks in the router will fail loudly when a new
 * venue is added to the type but not to the resolver.
 */
export type BrokerVenue = 'alpaca' | 'paper' | 'kraken' | 'hyperliquid';

export interface PlaceOrderInput {
  /** Ticker symbol, venue-native format. E.g. 'SPY' / 'AAPL' for equities. */
  symbol: string;
  side: 'buy' | 'sell';
  orderType: 'market' | 'limit';
  /**
   * Whole-share quantity. Phase A is whole-shares-only (SPEC §7 item 5);
   * fractional handling lands in Phase B.1.
   */
  qty: number;
  /**
   * Required iff orderType === 'limit'. Otherwise must be undefined —
   * adapters should reject a limitPrice on a market order rather than
   * silently ignoring it (avoids a class of operator-error bugs).
   */
  limitPrice?: number;
  /**
   * Repo-generated UUID. The broker dedupes by this ID; identical IDs
   * across retries MUST resolve to the same broker-side order. SPEC §7
   * item 3 is non-negotiable for live correctness.
   */
  clientOrderId: string;
  /** Day-only initially; GTC / IOC are deferred until a strategy needs them. */
  timeInForce: 'day';
}

export interface OrderHandle {
  /** Broker-assigned order ID. Echoed back on every status poll. */
  brokerOrderId: string;
  venue: BrokerVenue;
  /** Mirror of the input clientOrderId — useful for reconciliation. */
  clientOrderId: string;
  placedAt: Date;
}

/**
 * One status snapshot for an order. The fill-reconciliation loop
 * (Phase C) polls this until `status` reaches a terminal value:
 *   - 'filled' / 'canceled' / 'rejected' are terminal.
 *   - 'pending' / 'partially_filled' are in-flight.
 */
export interface OrderStatus {
  status: 'pending' | 'filled' | 'partially_filled' | 'canceled' | 'rejected';
  /** Shares filled so far. 0 while pending; equals qty at terminal-filled. */
  filledQty: number;
  /** Volume-weighted average fill price. null while filledQty === 0. */
  avgFillPrice: number | null;
  /**
   * Fees as reported by the broker (not estimated via fee_model.ts).
   * Reconciliation surfaces drift between this and the pre-trade quote.
   */
  feesUsd: number;
  /** Populated when status === 'rejected'. */
  rejectionReason?: string;
}

export interface AccountSummary {
  /** Total equity (cash + market value of positions). */
  equityUsd: number;
  /** Cash available for new orders. */
  cashUsd: number;
  /** Whether the broker considers this account day-trade restricted. */
  patternDayTrader: boolean;
}

export interface BrokerPosition {
  symbol: string;
  /** Signed: positive long, negative short. Phase A is long-only. */
  qty: number;
  avgEntryPrice: number;
  marketValueUsd: number;
}

/**
 * The contract every broker implementation honors.
 *
 * Implementations:
 *   - src/server/brokers/paper.ts   — PaperBrokerAdapter (synthetic fills)
 *   - src/server/brokers/alpaca.ts  — AlpacaAdapter (Phase B; not yet shipped)
 *
 * The router in the daemon (Phase C) resolves which implementation to
 * use from (strategy.assetClass, source) — see SPEC §3 router diagram.
 */
export interface BrokerAdapter {
  readonly venue: BrokerVenue;

  /**
   * Submit an order. MUST be idempotent on `clientOrderId`: a retry with
   * the same clientOrderId returns the same OrderHandle without opening
   * a duplicate position.
   */
  placeOrder(input: PlaceOrderInput): Promise<OrderHandle>;

  /**
   * Read the latest status for a previously-placed order. Used by the
   * fill-reconciliation loop. Should NOT throw on terminal statuses;
   * 'rejected' is a normal terminal outcome, not an exception.
   */
  getOrderStatus(handle: OrderHandle): Promise<OrderStatus>;

  /**
   * Cancel an in-flight order. Safe to call on terminal-status orders
   * (no-op). Throws on broker errors (network, auth).
   */
  cancelOrder(handle: OrderHandle): Promise<void>;

  /** Read account snapshot. Used for PDT detection + cash sizing. */
  getAccount(): Promise<AccountSummary>;

  /** List broker-confirmed open positions. Used for drift detection. */
  getPositions(): Promise<BrokerPosition[]>;
}

/**
 * What could break this:
 *   - Idempotency breakage at the implementation level — covered by
 *     SPEC §6 Phase B tests; cannot be enforced at the type level.
 *   - Venue union drift — when a new venue is added, both this union
 *     AND the daemon's router must be updated. The router uses an
 *     exhaustive switch on BrokerVenue so missed venues cause a tsc
 *     failure at compile time, not a runtime fallthrough.
 */
