/**
 * Historical regime fixtures — SPEC §5.2 (ARCHIVED, phase1_v2-only).
 *
 * **Status:** archived as of the phase1_v3 ramp. Every sub-test now
 * skips with a clear pointer to the live v3 fixture suite. The file
 * remains in the codebase as a historical reference — the 4 ADR-037
 * failures it pinned (2008_gfc / 2011_eu_debt / 2014_calm / 2020_covid)
 * are the empirical evidence motivating the v3 rewrite, so deleting
 * the file would lose that context.
 *
 * For the LIVE fixture suite under phase1_v3 see
 * `scripts/tests/macroRegimeFixturesV3.test.ts`. That suite reads the
 * persisted v3 backfill from CH (rather than re-running the v2
 * classifier on in-memory CSVs) and pins the v3 red-day distribution at
 * the same 4 historical windows — all 4 currently pass.
 *
 * Each fixture below is a CSV of real VIX/VIX3M/HYG/SPY/breadth values
 * for a named window, originally generated by
 * `scripts/_emit_macro_regime_fixtures.ts` after `npm run macro:ingest`.
 * The fixtures and the bundle-loader code are preserved verbatim so a
 * future engineer who needs to re-validate v2 logic against the same
 * windows can drop the skip block and rerun.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  classifyDateRangeFromBundle,
  type RegimeDataBundle,
  type Regime,
} from '../../src/server/macro_regime.js';

const FIXTURE_DIR = path.join(
  process.cwd(),
  'scripts',
  'tests',
  'fixtures',
  'macro_regime'
);

interface CsvRow {
  trade_date: string;
  vix_close: number | null;
  vix3m_close: number | null;
  hyg_close: number | null;
  spy_close: number | null;
  pct_above_50dma: number | null;
  breadth_source: string;
}

function parseCell(s: string): number | null {
  if (s === '' || s == null) return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

function loadFixture(name: string): CsvRow[] | null {
  const file = path.join(FIXTURE_DIR, `${name}.csv`);
  if (!fs.existsSync(file)) return null;
  const text = fs.readFileSync(file, 'utf-8').trim();
  if (!text) return null;
  const lines = text.split(/\r?\n/);
  // Skip header.
  return lines.slice(1).map(line => {
    const [trade_date, v, v3, h, s, p, src] = line.split(',');
    return {
      trade_date,
      vix_close: parseCell(v),
      vix3m_close: parseCell(v3),
      hyg_close: parseCell(h),
      spy_close: parseCell(s),
      pct_above_50dma: parseCell(p),
      breadth_source: src ?? '',
    };
  });
}

function bundleFromFixture(rows: CsvRow[], windowStart: string, windowEnd: string): RegimeDataBundle {
  const spyDates: string[] = [];
  const spyByDate = new Map<string, number>();
  const hygDates: string[] = [];
  const hygByDate = new Map<string, number>();
  const vixByDate = new Map<string, number>();
  const vix3mByDate = new Map<string, number>();
  const breadthByDate = new Map<string, { pct: number; source: string }>();

  for (const r of rows) {
    if (r.spy_close != null) {
      spyDates.push(r.trade_date);
      spyByDate.set(r.trade_date, r.spy_close);
    }
    if (r.hyg_close != null) {
      hygDates.push(r.trade_date);
      hygByDate.set(r.trade_date, r.hyg_close);
    }
    if (r.vix_close != null) vixByDate.set(r.trade_date, r.vix_close);
    if (r.vix3m_close != null) vix3mByDate.set(r.trade_date, r.vix3m_close);
    if (r.pct_above_50dma != null) {
      breadthByDate.set(r.trade_date, { pct: r.pct_above_50dma, source: r.breadth_source });
    }
  }

  const classifyDates = spyDates.filter(d => d >= windowStart && d <= windowEnd);
  return {
    classifyDates,
    spyDates,
    spyByDate,
    hygDates,
    hygByDate,
    vixByDate,
    vix3mByDate,
    breadthByDate,
  };
}

interface FixtureSpec {
  name: string;
  windowStart: string;
  windowEnd: string;
  /** Predicate the resulting regime sequence must satisfy. */
  expect: (regimes: Regime[]) => string | null; // null = pass; string = error message
}

const FIXTURES: FixtureSpec[] = [
  {
    name: '2008_gfc',
    windowStart: '2008-08-01', windowEnd: '2009-03-31',
    expect: regs => {
      const reds = regs.filter(r => r === 'red').length;
      // Sustained red across MOST days of the GFC peak — rough lower bound 30%.
      // The exact fraction depends on VIX3M availability before 2007-12-04 (which
      // doesn't apply here — the window starts well after).
      return reds / regs.length >= 0.3
        ? null
        : `expected red >= 30% during GFC peak, got ${(reds / regs.length * 100).toFixed(1)}%`;
    },
  },
  {
    name: '2011_eu_debt',
    windowStart: '2011-08-01', windowEnd: '2011-09-30',
    expect: regs => {
      const stress = regs.filter(r => r === 'orange' || r === 'red').length;
      return stress >= 5
        ? null
        : `expected >=5 orange-or-red days in Aug-Sep 2011, got ${stress}`;
    },
  },
  {
    name: '2014_calm',
    windowStart: '2014-04-01', windowEnd: '2014-09-30',
    expect: regs => {
      const reds = regs.filter(r => r === 'red').length;
      const greens = regs.filter(r => r === 'green').length;
      if (reds > 0) return `quiet 2014 fixture must have zero red days, got ${reds}`;
      if (greens / regs.length < 0.7) return `quiet 2014 should be majority green, got ${(greens / regs.length * 100).toFixed(1)}%`;
      return null;
    },
  },
  {
    name: '2018_q4_selloff',
    windowStart: '2018-10-01', windowEnd: '2018-12-31',
    expect: regs => {
      const stress = regs.filter(r => r === 'orange' || r === 'red').length;
      return stress >= 3
        ? null
        : `expected >=3 orange-or-red days in 2018-Q4 selloff, got ${stress}`;
    },
  },
  {
    name: '2020_covid',
    windowStart: '2020-02-19', windowEnd: '2020-04-30',
    expect: regs => {
      const reds = regs.filter(r => r === 'red').length;
      return reds >= 5
        ? null
        : `expected >=5 red days during 2020 COVID crash, got ${reds}`;
    },
  },
];

describe('macro regime — historical fixtures (SPEC §5.2, ARCHIVED phase1_v2)', () => {
  for (const f of FIXTURES) {
    it(`${f.name} (${f.windowStart} → ${f.windowEnd}) [ARCHIVED]`, (t) => {
      t.skip(
        'phase1_v2 fixture archived after the phase1_v3 ramp — see ' +
          'scripts/tests/macroRegimeFixturesV3.test.ts for the live suite. ' +
          'The bundle-loader code below is preserved verbatim for re-validation.',
      );
    });
  }

  it('2017 holdout — distribution recorded only [ARCHIVED]', (t) => {
    t.skip(
      'phase1_v2 holdout archived after the phase1_v3 ramp — see the v3 suite for live coverage',
    );
  });
});

// Mark imports as intentionally retained for re-validation paths. Without
// this the linter would flag them after the ramp's skip-out.
void classifyDateRangeFromBundle;
void loadFixture;
void bundleFromFixture;
const _archivedFixtureCount: number = FIXTURES.length;
void _archivedFixtureCount;
